title: Martin Scholz
email: martin@scholz.technology
description: >-
  Data & AI leadership, architecture and real-world delivery for complex enterprise systems
baseurl: ""
url: ""
theme: minima
plugins:
  - jekyll-seo-tag
